-- V1: 초기 스키마 (현재 엔티티로 빈 DB 에 생성한 pg_dump 를 정리한 것)
-- 이후 엔티티 변경은 V2, V3 ... 로 추가한다. 이 파일은 수정하지 않는다.

CREATE TABLE public.board_game (
    max_players integer NOT NULL,
    min_players integer NOT NULL,
    offline_available boolean DEFAULT true NOT NULL,
    online_available boolean DEFAULT false NOT NULL,
    play_time integer NOT NULL,
    stock integer DEFAULT 1 NOT NULL,
    visible boolean DEFAULT true NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    youtube_video_id character varying(11),
    difficulty character varying(20) NOT NULL,
    image_key character varying(100),
    name character varying(100) NOT NULL,
    description text,
    CONSTRAINT board_game_difficulty_check CHECK (((difficulty)::text = ANY ((ARRAY['EASY'::character varying, 'NORMAL'::character varying, 'HARD'::character varying])::text[])))
);

CREATE TABLE public.member (
    birth_date date,
    admin_requested_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    admin_request_status character varying(20) NOT NULL,
    avatar_emoji character varying(20) NOT NULL,
    avatar_type character varying(20) NOT NULL,
    name character varying(20),
    nickname character varying(20) NOT NULL,
    role character varying(20) NOT NULL,
    affiliation character varying(50),
    job character varying(50),
    avatar_image_key character varying(100),
    bio character varying(100),
    email character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    CONSTRAINT member_admin_request_status_check CHECK (((admin_request_status)::text = ANY ((ARRAY['NONE'::character varying, 'PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[]))),
    CONSTRAINT member_avatar_type_check CHECK (((avatar_type)::text = ANY ((ARRAY['EMOJI'::character varying, 'IMAGE'::character varying])::text[]))),
    CONSTRAINT member_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying, 'SUPER_ADMIN'::character varying])::text[])))
);

CREATE TABLE public.notification (
    is_read boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    receiver_id bigint NOT NULL,
    type character varying(30) NOT NULL,
    link character varying(100),
    message character varying(200) NOT NULL,
    CONSTRAINT notification_type_check CHECK (((type)::text = ANY ((ARRAY['PARTY_JOINED'::character varying, 'PARTY_FULL'::character varying, 'PARTY_LEFT'::character varying, 'PARTY_KICKED'::character varying, 'PARTY_CLOSED'::character varying, 'GAME_SUSPENDED'::character varying, 'RESERVATION_REQUESTED'::character varying, 'RESERVATION_APPROVED'::character varying, 'RESERVATION_REJECTED'::character varying, 'RESERVATION_CANCELLED'::character varying, 'ADMIN_REQUESTED'::character varying, 'ADMIN_APPROVED'::character varying, 'ADMIN_REJECTED'::character varying])::text[])))
);

CREATE TABLE public.party (
    capacity integer NOT NULL,
    board_game_id bigint,
    created_at timestamp(6) without time zone NOT NULL,
    host_id bigint NOT NULL,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    play_at timestamp(6) without time zone,
    play_mode character varying(20) DEFAULT 'OFFLINE'::character varying NOT NULL,
    status character varying(20) NOT NULL,
    online_platform character varying(30),
    custom_game_name character varying(50),
    location character varying(100),
    title character varying(100) NOT NULL,
    online_link character varying(300),
    description text,
    CONSTRAINT party_play_mode_check CHECK (((play_mode)::text = ANY ((ARRAY['ONLINE'::character varying, 'OFFLINE'::character varying])::text[]))),
    CONSTRAINT party_status_check CHECK (((status)::text = ANY ((ARRAY['RECRUITING'::character varying, 'CLOSED'::character varying, 'CANCELLED'::character varying])::text[])))
);

CREATE TABLE public.party_member (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    joined_at timestamp(6) without time zone NOT NULL,
    member_id bigint NOT NULL,
    party_id bigint NOT NULL,
    status character varying(10) DEFAULT 'JOINED'::character varying NOT NULL,
    CONSTRAINT party_member_status_check CHECK (((status)::text = ANY ((ARRAY['JOINED'::character varying, 'KICKED'::character varying])::text[])))
);

CREATE TABLE public.reservation (
    end_date date NOT NULL,
    start_date date NOT NULL,
    board_game_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    decided_at timestamp(6) without time zone,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id bigint NOT NULL,
    cancel_reason character varying(20),
    status character varying(20) NOT NULL,
    reject_reason character varying(100),
    CONSTRAINT reservation_cancel_reason_check CHECK (((cancel_reason)::text = ANY ((ARRAY['MEMBER'::character varying, 'GAME_SUSPENDED'::character varying])::text[]))),
    CONSTRAINT reservation_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying])::text[])))
);

ALTER TABLE ONLY public.board_game
    ADD CONSTRAINT board_game_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.member
    ADD CONSTRAINT member_email_key UNIQUE (email);

ALTER TABLE ONLY public.member
    ADD CONSTRAINT member_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.party_member
    ADD CONSTRAINT party_member_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.party
    ADD CONSTRAINT party_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT reservation_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.party_member
    ADD CONSTRAINT uk_party_member UNIQUE (party_id, member_id);

CREATE INDEX idx_notification_receiver_read_created ON public.notification USING btree (receiver_id, is_read, created_at);

CREATE INDEX idx_reservation_game_period ON public.reservation USING btree (board_game_id, start_date, end_date);

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fk1jpw68rbaxvu8u5l1dniain1l FOREIGN KEY (receiver_id) REFERENCES public.member(id);

ALTER TABLE ONLY public.board_game
    ADD CONSTRAINT fk4qjyjalnhbok1yv44qv3buvlu FOREIGN KEY (created_by) REFERENCES public.member(id);

ALTER TABLE ONLY public.party
    ADD CONSTRAINT fk5lvpb3go603pekfj5ekjsavtv FOREIGN KEY (host_id) REFERENCES public.member(id);

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fk68999qe28ym9eqqlowybh9nvn FOREIGN KEY (member_id) REFERENCES public.member(id);

ALTER TABLE ONLY public.party_member
    ADD CONSTRAINT fkctrpcp93h130dwe6j1jlhf960 FOREIGN KEY (party_id) REFERENCES public.party(id);

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT fkdhytd6s5s6ymtcmnl5odny5i6 FOREIGN KEY (board_game_id) REFERENCES public.board_game(id);

ALTER TABLE ONLY public.party
    ADD CONSTRAINT fkg34yejgessse53hiiidfkf0e5 FOREIGN KEY (board_game_id) REFERENCES public.board_game(id);

ALTER TABLE ONLY public.party_member
    ADD CONSTRAINT fknysnaqwxtvpxoos0ycwtklbou FOREIGN KEY (member_id) REFERENCES public.member(id);
